# Generated by Django 5.2.4 on 2025-07-19 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="نام و نام خانوادگی"),
                ),
                ("phone", models.CharField(max_length=15, verbose_name="شماره تماس")),
                ("email", models.EmailField(max_length=254, verbose_name="ایمیل")),
                (
                    "payment_type",
                    models.CharField(
                        choices=[("cash", "نقدی"), ("installment", "اقساطی")],
                        max_length=20,
                        verbose_name="نوع پرداخت",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار پرداخت"),
                            ("paid", "پرداخت شده"),
                            ("failed", "ناموفق"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="وضعیت پرداخت",
                    ),
                ),
                ("amount", models.IntegerField(verbose_name="مبلغ (تومان)")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ثبت"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "ثبت نام",
                "verbose_name_plural": "ثبت نام ها",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "authority",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="کد پیگیری زرین پال",
                    ),
                ),
                (
                    "ref_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="کد مرجع پرداخت",
                    ),
                ),
                ("amount", models.IntegerField(verbose_name="مبلغ (تومان)")),
                (
                    "is_paid",
                    models.BooleanField(default=False, verbose_name="پرداخت شده"),
                ),
                (
                    "payment_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ پرداخت"
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="registration.registration",
                    ),
                ),
            ],
            options={
                "verbose_name": "پرداخت",
                "verbose_name_plural": "پرداخت ها",
            },
        ),
    ]
