# Generated by Django 5.2.4 on 2025-07-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="registration",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "ثبت نام",
                "verbose_name_plural": "ثبت نام\u200cها",
            },
        ),
        migrations.AddField(
            model_name="registration",
            name="tracking_code",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="کد پیگیری",
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="amount",
            field=models.IntegerField(verbose_name="مبلغ"),
        ),
        migrations.AlterField(
            model_name="registration",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ثبت نام"),
        ),
        migrations.AlterField(
            model_name="registration",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="ایمیل"
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="payment_type",
            field=models.CharField(
                choices=[("cash", "نقدی"), ("installment", "اقساطی")],
                default="cash",
                max_length=20,
                verbose_name="نوع پرداخت",
            ),
        ),
    ]
