# Generated by Django 5.2.4 on 2025-07-19 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0002_alter_registration_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={
                "ordering": ["-payment_date"],
                "verbose_name": "پرداخت",
                "verbose_name_plural": "پرداخت ها",
            },
        ),
        migrations.AlterModelOptions(
            name="registration",
            options={
                "ordering": ["-registration_date"],
                "verbose_name": "ثبت نام",
                "verbose_name_plural": "ثبت نام ها",
            },
        ),
        migrations.RenameField(
            model_name="registration",
            old_name="created_at",
            new_name="registration_date",
        ),
        migrations.RemoveField(
            model_name="registration",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="registration",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.IntegerField(verbose_name="مبلغ"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="authority",
            field=models.CharField(max_length=100, verbose_name="شناسه پرداخت"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="ref_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="شناسه مرجع"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="registration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="registration.registration",
                verbose_name="ثبت نام",
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="ایمیل"),
        ),
        migrations.AlterField(
            model_name="registration",
            name="name",
            field=models.CharField(max_length=100, verbose_name="نام و نام خانوادگی"),
        ),
        migrations.AlterField(
            model_name="registration",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "در انتظار پرداخت"),
                    ("paid", "پرداخت شده"),
                    ("failed", "پرداخت ناموفق"),
                ],
                default="pending",
                max_length=20,
                verbose_name="وضعیت پرداخت",
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="payment_type",
            field=models.CharField(
                choices=[("cash", "پرداخت نقدی"), ("installment", "پرداخت اقساطی")],
                default="cash",
                max_length=20,
                verbose_name="نوع پرداخت",
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="phone",
            field=models.CharField(max_length=11, verbose_name="شماره تماس"),
        ),
        migrations.AlterField(
            model_name="registration",
            name="tracking_code",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                unique=True,
                verbose_name="کد پیگیری",
            ),
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="موضوع"
                    ),
                ),
                ("content", models.TextField(verbose_name="متن پیام")),
                (
                    "message_type",
                    models.CharField(
                        choices=[("sms", "پیامک"), ("email", "ایمیل")],
                        default="sms",
                        max_length=10,
                        verbose_name="نوع پیام",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار ارسال"),
                            ("sent", "ارسال شده"),
                            ("failed", "ارسال ناموفق"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="وضعیت ارسال",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ ارسال"
                    ),
                ),
                (
                    "recipients",
                    models.ManyToManyField(
                        related_name="messages",
                        to="registration.registration",
                        verbose_name="دریافت کنندگان",
                    ),
                ),
            ],
            options={
                "verbose_name": "پیام",
                "verbose_name_plural": "پیام ها",
                "ordering": ["-created_at"],
            },
        ),
    ]
