# Generated by Django 5.2.4 on 2025-07-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "registration",
            "0003_alter_payment_options_alter_registration_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="ایمیل"
            ),
        ),
    ]
