# Generated by Django 5.2.4 on 2025-07-20 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0004_alter_registration_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registration",
            name="email",
        ),
    ]
